'use strict';

const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const staticItalian = new Map($$('[data-i18n]').map(element => [element.dataset.i18n, element.innerHTML]));
const attrItalian = new Map($$('[data-i18n-aria], [data-i18n-alt]').map(element => [element.dataset.i18nAria || element.dataset.i18nAlt, element.getAttribute(element.dataset.i18nAria ? 'aria-label' : 'alt')]));

const en = {
    skip: 'Skip to content', brandHome: 'Cronisto, home', navLabel: 'Cronisto navigation', navJourney: 'The journey', navAi: 'AI with you', navScenarios: 'Scenarios', backHome: '&larr; Rosario Moscato', languageLabel: 'Select language', headerCta: 'Discover the beta <span aria-hidden="true">&nearr;</span>', heroEyebrow: '<span class="status-dot" aria-hidden="true"></span> AI-ASSISTED PROJECT MANAGEMENT', heroTitle: 'Ideas<br>become<br><em>projects.</em>', heroLead: 'Shape the brief. Connect decisions.<br>Take the work through to delivery.', heroPrimary: 'See how it takes shape <span aria-hidden="true">&nearr;</span>', openCronisto: 'Open Cronisto <span aria-hidden="true">&nearr;</span>', heroMicro: 'Cronisto is invite-only beta.', consoleLabel: 'Cronisto app preview', consoleProject: 'cronisto / project in progress', consoleStatus: 'CONTEXT ACTIVE', consoleAlt: 'Dark screen of Cronisto beta access', consoleCaption: '&gt; from brief to plan, without losing the why', heroBottom: 'THE CONTEXT STAYS. THE PROJECT MOVES FORWARD.', scrollExplore: 'Scroll to explore <span aria-hidden="true">&darr;</span>',
    problemEyebrow: '01 / THE STARTING POINT', problemTitle: 'One project.<br><span>Too much scattered information.</span>', problemLead: 'Briefs in documents. Decisions in chats. Estimates in spreadsheets.<br>Cronisto connects what is needed to take action.', comparisonHeading: 'WORK CHANGES WHEN CONTEXT STAYS', comparisonLabel: 'Compare ways of working', compareBefore: 'Scattered information', compareAfter: 'With Cronisto', journeyEyebrow: '02 / EXPLORE THE JOURNEY', journeyTitle: 'One brief.<br><span>A whole project.</span>', journeyLead: 'Follow information as it takes shape.<br>Choose an example, then explore every step.', projectLabel: 'Choose the example project', projectPortal: 'Client portal', projectWebsite: 'Company website', projectInternal: 'Internal tool', projectNote: 'Illustrative examples, sample content', stepsLabel: 'Project steps', step0: 'Brief', step1: 'Requirements', step2: 'Plan', step3: 'Estimates', step4: 'Costs', step5: 'Documents', step6: 'Delivery', step7: 'Decisions', previousStage: 'Previous step', nextStage: 'Next step', guidedExample: 'Guided example',
    aiEyebrow: '03 / ARTIFICIAL INTELLIGENCE, HUMAN JUDGEMENT', aiTitle: 'AI shapes it.<br><span>You set the direction.</span>', aiLead: 'Requirements, plans, estimates and summaries: AI prepares proposals you can review. Final approval stays with you.', principle1: 'Proposals always start as drafts', principle2: 'Review before approval', principle3: 'Control over decisions', approvalTop: 'A proposal to assess', approvalEyebrow: 'CLIENT PORTAL REQUIREMENTS', approvalTitle: 'The brief starts<br>becoming clear.', demoDisclosure: 'Demonstration interaction. No AI is run.',
    scenariosEyebrow: '04 / ESTIMATES TO EXPLAIN, OFFERS TO DISCUSS', scenariosTitle: 'One plan.<br><span>More ways to deliver it.</span>', scenariosLead: 'Compare the contribution of people and AI.<br>Make assumptions explicit before preparing an offer.', scenarioLabel: 'Delivery scenario', scenarioHuman: '<span>01</span>Human <small>Team experience and availability</small>', scenarioAi: '<span>02</span>AI <small>Delivery assumptions with models</small>', scenarioHybrid: '<span>03</span>Hybrid <small>Different contributions, one shared plan</small>', scenarioFooterTitle: 'Assumptions become a PDF proposal.', scenarioFooterLead: 'Selectable scenarios. Direct and recurring costs. Documents in Italian or English.', scenarioDisclaimer: 'Estimates to assess,<br>no savings guaranteed.',
    continuityEyebrow: '05 / CONTEXT SUPPORTS THE WORK', continuityTitle: 'From the proposal<br><span>to those who deliver it.</span>', continuityLead: 'Documents for the client. Prompts for the team or an AI agent.<br>Tasks and decisions in the same workspace.', handoff1Title: 'Propose', handoff1Lead: 'Project presentation<br>Offer with selected scenarios', handoff2Title: 'Hand off', handoff2Lead: 'Detailed plan with Gantt<br>Prompts in Markdown too', handoff3Title: 'Deliver', handoff3Lead: 'Tasks, assignments and deadlines<br>Comments and decisions with history', trust1Title: 'Private access', trust1Lead: 'Owners and authorised members. Application not indexed.', trust2Lead: 'For every private attachment.', trust3Title: '30 <span>days</span>', trust3Lead: 'History of encrypted daily backups.', trust4Title: 'Revocable control', trust4Lead: 'External agents with the user permissions. Actions tracked.',
    audienceEyebrow: '06 / WHERE IT CAN MAKE A DIFFERENCE', audienceTitle: 'Your next<br>project, <span>clearer.</span>', audienceLead: 'For people who need to define, propose and coordinate work.', audience1Title: 'Digital agencies <span aria-hidden="true">+</span>', audience1Lead: 'Connect the client brief to the plan and offer. Keep requests visible as the project moves from sales to the team.', audience2Title: 'Software companies <span aria-hidden="true">+</span>', audience2Lead: 'Connect functional and non-functional requirements to tasks. Make coverage, dependencies and technical decisions visible.', audience3Title: 'Consultants and freelance PMs <span aria-hidden="true">+</span>', audience3Lead: 'Structure proposals, estimates and deliveries. Coordinate internal and external resources and reuse existing projects as templates.', audience4Title: 'Product teams <span aria-hidden="true">+</span>', audience4Lead: 'Keep the context of decisions and track priorities and progress. Find tasks, comments and attachments in the project.', audience5Title: 'Companies and suppliers <span aria-hidden="true">+</span>', audience5Lead: 'Align the people requesting the work with those delivering it. Share documents, assign tasks and make decisions available.', closingEyebrow: 'THE NEXT STEP IS A REAL PROJECT', closingTitle: 'Your idea.<br><span>Its next step.</span>', closingLead: 'Bring a brief to clarify.<br>Discover Cronisto and request a demo.', closingCta: 'Discover the invite-only beta <span aria-hidden="true">&nearr;</span>', footerBeta: 'Invite-only beta'
};

en.consoleAlt = 'Dark screen of Cronisto project flow';

const content = {
    it: {
        projects: { portal: ['Portale clienti', 'Vorremmo un portale dove i clienti possano seguire i progetti e condividere i documenti.', 'Clienti e team', 'Accessi e permessi', ['Accesso riservato ai clienti', 'Condivisione dei documenti', "Visibilita' secondo i permessi"], ['Definire i permessi', "Realizzare l'area clienti", 'Verificare gli accessi'], "Visibilita' dei documenti per progetto"], website: ['Sito aziendale', "Vogliamo un sito che racconti i nostri servizi e renda piu' semplice ricevere richieste dai potenziali clienti.", 'Marketing e visitatori', 'Contenuti e contatti', ['Pagine dei servizi', 'Modulo di contatto', 'Navigazione accessibile'], ['Definire i contenuti', 'Realizzare le pagine', 'Verificare i percorsi'], 'Struttura delle pagine dei servizi'], internal: ['Strumento interno', 'Ci serve uno spazio per raccogliere le richieste interne, assegnarle e seguirne lo stato.', 'Team e responsabili', "Ruoli e priorita'", ['Raccolta delle richieste', 'Assegnazione ai responsabili', 'Accesso secondo il ruolo'], ['Definire i ruoli', 'Creare il flusso richieste', 'Verificare le assegnazioni'], "Responsabilita' nell'approvazione delle richieste"] },
        stages: [['IL PUNTO DI PARTENZA', "Basta un'idea<br>da chiarire.", "Descrivi cosa vuoi ottenere, per chi e con quali vincoli. Il brief e' il primo contesto condiviso."], ["L'AI PROPONE, TU RIVEDI", 'Le richieste<br>prendono forma.', "L'AI propone requisiti funzionali e non funzionali. Restano in bozza finche' non li rivedi e approvi."], ['COLLEGAMENTI VISIBILI', 'Il cosa diventa<br>un come.', 'I requisiti approvati generano wave e task. Dipendenze, date e Gantt rendono leggibile la sequenza.'], ['IPOTESI ESPLICITE', 'Il lavoro incontra<br>le risorse.', "Stima ogni task in giorni uomo, giorni AI o modalita' ibrida."], ['UNA VISIONE ECONOMICA', 'Ogni costo<br>ha un contesto.', 'Considera costi diretti, ricorrenti e ripartiti sul periodo.'], ['PRONTI DA CONDIVIDERE', "Il progetto<br>si puo' raccontare.", 'Presentazione, piano, offerta e prompt operativo.'], ['IL LAVORO QUOTIDIANO', "Il piano diventa<br>attivita'.", "Assegnazioni, scadenze, priorita' e checklist."], ['IL CONTESTO CHE RESTA', 'Ogni scelta<br>ha una storia.', 'Decisioni tecniche, business e progettuali restano consultabili.']],
        comparison: { before: [['«Cosa aveva chiesto il cliente?»', "Il brief e' vago. Il perimetro continua a cambiare."], ['«Su cosa si basa questa stima?»', 'Le ipotesi sono implicite. I margini restano esposti.'], ["«Perche' avevamo deciso cosi'?»", 'Le motivazioni si perdono nei passaggi di consegne.']], after: [['Requisiti collegati al lavoro', 'Requisiti approvati, task e copertura visibile.'], ['Ipotesi economiche esplicite', "Attivita', risorse, tariffe e scenari confrontabili."], ['Decisioni con una memoria', 'Storico e motivazioni nel contesto del progetto.']] }
    },
    en: {
        projects: { portal: ['Client portal', 'We would like a portal where clients can follow projects and share documents.', 'Clients and team', 'Access and permissions', ['Client-only access', 'Document sharing', 'Permission-based visibility'], ['Define permissions', 'Build the client area', 'Check access'], 'Document visibility by project'], website: ['Company website', 'We want a website that presents our services and makes it easier to receive enquiries from prospective clients.', 'Marketing and visitors', 'Content and contacts', ['Service pages', 'Contact form', 'Accessible navigation'], ['Define content', 'Build the pages', 'Check user journeys'], 'Service page structure'], internal: ['Internal tool', 'We need a space to collect internal requests, assign them and follow their status.', 'Team and managers', 'Roles and priorities', ['Request collection', 'Assignment to managers', 'Role-based access'], ['Define roles', 'Create request flow', 'Check assignments'], 'Responsibility for approving requests'] },
        stages: [['THE STARTING POINT', 'An idea<br>to clarify.', 'Describe what you want to achieve, for whom, and with which constraints. The brief is the first shared context.'], ['AI PROPOSES, YOU REVIEW', 'Requests<br>take shape.', 'AI proposes functional and non-functional requirements. They remain drafts until you review and approve them.'], ['VISIBLE CONNECTIONS', 'What becomes<br>how.', 'Approved requirements generate waves and tasks. Dependencies, dates and Gantt make the sequence readable.'], ['EXPLICIT ASSUMPTIONS', 'Work meets<br>resources.', 'Estimate every task in person-days, AI-days or hybrid mode.'], ['AN ECONOMIC VIEW', 'Every cost<br>has context.', 'Consider direct, recurring and period-allocated costs.'], ['READY TO SHARE', 'The project<br>can be told.', 'Presentation, plan, offer and operational prompt.'], ['DAILY WORK', 'The plan becomes<br>activity.', 'Assignments, deadlines, priorities and checklists.'], ['CONTEXT THAT STAYS', 'Every choice<br>has a history.', 'Technical, business and project decisions remain available.']],
        comparison: { before: [['“What had the client asked for?”', 'The brief is vague. The scope keeps changing.'], ['“What is this estimate based on?”', 'Assumptions are implicit. Margins remain exposed.'], ['“Why had we decided that?”', 'Reasons get lost in handoffs.']], after: [['Requirements connected to work', 'Approved requirements, tasks and visible coverage.'], ['Explicit financial assumptions', 'Activities, resources, rates and comparable scenarios.'], ['Decisions with a memory', 'History and reasoning in the project context.']] }
    }
};

let language = localStorage.getItem('lang') === 'en' ? 'en' : 'it';
let selectedProject = 'portal'; let selectedStage = 0; let selectedScenario = 'hybrid'; let approved = false;
const text = () => content[language];
const project = () => { const p = text().projects[selectedProject]; return { name: p[0], brief: p[1], people: p[2], question: p[3], requirements: p[4], tasks: p[5], decision: p[6] }; };
const words = () => language === 'en' ? { of: 'of', recipients: 'Recipients', clarify: 'To clarify', review: 'To review', functional: 'Functional requirement', nonfunctional: 'Non-functional requirement', linked: 'Linked to requirement', analysis: 'Analysis', build: 'Build', check: 'Check', context: 'This is where the project context begins.', human: 'Human days', ai: 'AI days', hybrid: 'Hybrid mode', direct: 'Direct costs', recurring: 'Recurring costs', documents: 'PROJECT DOCUMENTS', tasks: 'TEAM TASKS', decisions: 'DECISION MEMORY', inProgress: 'In progress', planned: 'Planned', approve: 'Approve proposal', revise: 'Review draft', draft: 'AI draft', approved: 'Approved by you', choice: 'The choice is yours.', waiting: 'This proposal is waiting for your review.', approvedTitle: 'You approved the proposal.', approvedLead: 'In the Cronisto journey, approved requirements feed the plan.' } : { of: 'di', recipients: 'Destinatari', clarify: 'Da chiarire', review: 'Da rivedere', functional: 'Requisito funzionale', nonfunctional: 'Requisito non funzionale', linked: 'Collegato al requisito', analysis: 'Analisi', build: 'Realizzazione', check: 'Verifica', context: 'Qui inizia il contesto del progetto.', human: 'Giorni uomo', ai: 'Giorni AI', hybrid: "Modalita' ibrida", direct: 'Costi diretti', recurring: 'Costi ricorrenti', documents: 'DOCUMENTI DEL PROGETTO', tasks: 'ATTIVITA\' DEL TEAM', decisions: 'MEMORIA DELLE DECISIONI', inProgress: 'In corso', planned: 'In piano', approve: 'Approva la proposta', revise: 'Rivedi la bozza', draft: 'Bozza AI', approved: 'Approvato da te', choice: "La scelta e' tua.", waiting: 'Questa proposta attende la tua revisione.', approvedTitle: 'Hai approvato la proposta.', approvedLead: 'Nel percorso Cronisto, i requisiti approvati alimentano il piano.' };

function stageMarkup(p, step) { const w = words(); const note = value => `<div class="context-note"><b>✳</b>${value}</div>`; if (step === 0) return `<p class="workspace-eyebrow">${language === 'en' ? 'PROJECT BRIEF' : 'BRIEF DI PROGETTO'}</p><div class="brief-quote">&laquo;${p.brief}&raquo;</div><div class="brief-meta"><span>${w.recipients}<strong>${p.people}</strong></span><span>${w.clarify}<strong>${p.question}</strong></span></div>${note(w.context)}`; if (step === 1) return `<div class="view-heading"><p class="workspace-eyebrow">${language === 'en' ? 'REQUIREMENTS PROPOSAL' : 'PROPOSTA DI REQUISITI'}</p><span class="tiny-status">${w.review}</span></div><ul class="requirement-list">${p.requirements.map((item, i) => `<li><span>0${i + 1}</span><div>${item}<small>${i === 2 ? w.nonfunctional : w.functional}</small></div></li>`).join('')}</ul>`; if (step === 2) return `<p class="workspace-eyebrow">${language === 'en' ? 'PLAN AND TRACEABILITY' : 'PIANO E TRACCIABILITA\''}</p>${p.tasks.map((item, i) => `<div class="gantt-row"><span>${item}<small>${w.linked} ${i + 1}</small></span><div class="gantt-track"><span style="--offset:${i * 24}%;--length:${i === 0 ? 35 : 45}%">${[w.analysis, w.build, w.check][i]}</span></div></div>`).join('')}`; if (step === 6) return `<p class="workspace-eyebrow">${w.tasks}</p><div class="task-view">${p.tasks.map((item, i) => `<div><span class="task-check ${i === 0 ? 'checked' : ''}">${i === 0 ? '✓' : ''}</span><span>${item}<small>${i === 0 ? w.review : language === 'en' ? 'Assignment and priority' : "Assegnazione e priorita'"}</small></span><span class="task-state">${i === 0 ? w.inProgress : w.planned}</span></div>`).join('')}</div>`; return `<p class="workspace-eyebrow">${[language === 'en' ? 'HOW TO ESTIMATE ACTIVITIES' : 'COME STIMARE LE ATTIVITA\'', language === 'en' ? 'COST COMPONENTS' : 'COMPONENTI DEL COSTO', w.documents, w.decisions][step - 3] || ''}</p>${note(language === 'en' ? 'Illustrative project information.' : 'Informazioni illustrative del progetto.')}`; }
function renderStage() { const [kicker, title, description] = text().stages[selectedStage]; $('#stage-number').textContent = String(selectedStage + 1).padStart(2, '0'); $('#stage-kicker').textContent = kicker; $('#stage-title').innerHTML = title; $('#stage-description').textContent = description; $('#project-name').textContent = project().name; $('#stage-counter').textContent = `${selectedStage + 1} ${words().of} ${text().stages.length}`; $('#stage-prev').disabled = selectedStage === 0; $('#stage-next').disabled = selectedStage === text().stages.length - 1; $$('[data-step]').forEach(b => b.setAttribute('aria-pressed', String(Number(b.dataset.step) === selectedStage))); $('#stage-view').innerHTML = stageMarkup(project(), selectedStage); }
function renderComparison(key) { $('#comparison').classList.toggle('is-after', key === 'after'); $('#compare-content').innerHTML = text().comparison[key].map((row, i) => `<div class="compare-row content-in"><span class="row-index">0${i + 1}</span><h3>${row[0]}</h3><p>${row[1]}</p><span class="row-symbol" aria-hidden="true">${key === 'after' ? '✓' : '?'}</span></div>`).join(''); }
function renderScenario(key) { const scenarios = language === 'en' ? { human: ['HUMAN SCENARIO', 'The team\'s skills<br>in the plan.', 'An estimate based on person-days and the rates of involved resources.'], ai: ['AI SCENARIO', 'AI delivery,<br>with explicit assumptions.', 'An estimate of AI model contribution, to review in the project context.'], hybrid: ['HYBRID SCENARIO', 'People and AI.<br>Distinct contributions.', 'An estimate combining people\'s work and AI delivery.'] } : { human: ['SCENARIO UMANO', 'Le competenze<br>del team, nel piano.', 'Una stima basata sui giorni uomo e sulle tariffe delle risorse coinvolte.'], ai: ['SCENARIO AI', "L'esecuzione AI,<br>con ipotesi esplicite.", 'Una stima del contributo dei modelli AI, da rivedere nel contesto del progetto.'], hybrid: ['SCENARIO IBRIDO', 'Persone e AI.<br>Contributi distinti.', "Una stima che combina il lavoro delle persone e l'esecuzione AI."] }; const data = scenarios[key]; $('#scenario-detail').innerHTML = `<div class="content-in"><p class="eyebrow">${data[0]}</p><h3>${data[1]}</h3><p class="scenario-description">${data[2]}</p></div>`; }
function renderApproval() { const w = words(); const requirements = project().requirements; $('#approval-requirements').innerHTML = requirements.map((item, i) => `<li><span>0${i + 1}</span><div>${item}<small>${i === 2 ? w.nonfunctional : w.functional}</small></div></li>`).join(''); $('#approval-badge').textContent = approved ? w.approved : w.draft; $('#review-note').innerHTML = approved ? `<strong>${w.approvedTitle}</strong><span>${w.approvedLead}</span>` : `<strong>${w.choice}</strong><span>${w.waiting}</span>`; $('#approve').innerHTML = `${approved ? w.revise : w.approve} <span aria-hidden="true">${approved ? '↺' : '&nearr;'}</span>`; }
function setLanguage(next) { language = next === 'en' ? 'en' : 'it'; localStorage.setItem('lang', language); document.documentElement.lang = language; const strings = language === 'en' ? en : {}; $$('[data-i18n]').forEach(el => { el.innerHTML = strings[el.dataset.i18n] || staticItalian.get(el.dataset.i18n); }); $$('[data-i18n-aria], [data-i18n-alt]').forEach(el => { const key = el.dataset.i18nAria || el.dataset.i18nAlt; el.setAttribute(el.dataset.i18nAria ? 'aria-label' : 'alt', strings[key] || attrItalian.get(key)); }); document.title = language === 'en' ? 'Cronisto - Ideas become projects' : 'Cronisto - Le idee diventano progetti'; $('meta[name="description"]').content = language === 'en' ? 'From brief to requirements, from plan to offer and delivery. Discover Cronisto, AI-assisted project management.' : "Dal brief ai requisiti, dal piano all'offerta e all'esecuzione. Scopri Cronisto, il project management assistito dall'AI."; $('meta[property="og:title"]').content = document.title; $('meta[property="og:description"]').content = language === 'en' ? 'AI-assisted project management: from brief to plan, from cost scenarios to delivery.' : "Project management assistito dall'AI: dal brief al piano, dagli scenari di costo all'esecuzione."; $$('[data-lang]').forEach(b => b.setAttribute('aria-pressed', String(b.dataset.lang === language))); renderComparison($('[data-compare][aria-pressed="true"]').dataset.compare); renderStage(); renderScenario(selectedScenario); renderApproval(); }
$$('[data-step]').forEach(b => b.addEventListener('click', () => { selectedStage = Number(b.dataset.step); renderStage(); })); $('#stage-prev').addEventListener('click', () => { selectedStage = Math.max(0, selectedStage - 1); renderStage(); }); $('#stage-next').addEventListener('click', () => { selectedStage = Math.min(text().stages.length - 1, selectedStage + 1); renderStage(); }); $$('[data-project]').forEach(b => b.addEventListener('click', () => { selectedProject = b.dataset.project; $$('[data-project]').forEach(x => x.setAttribute('aria-pressed', String(x === b))); renderStage(); })); $$('[data-compare]').forEach(b => b.addEventListener('click', () => { $$('[data-compare]').forEach(x => x.setAttribute('aria-pressed', String(x === b))); renderComparison(b.dataset.compare); })); $$('[data-scenario]').forEach(b => b.addEventListener('click', () => { selectedScenario = b.dataset.scenario; $$('[data-scenario]').forEach(x => x.setAttribute('aria-pressed', String(x === b))); renderScenario(selectedScenario); })); $('#approve').addEventListener('click', () => { approved = !approved; $('#approval-demo').classList.toggle('is-approved', approved); renderApproval(); }); $$('[data-lang]').forEach(b => b.addEventListener('click', () => setLanguage(b.dataset.lang)));
const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches; if (!reducedMotion && 'IntersectionObserver' in window) { const observer = new IntersectionObserver(entries => entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('revealed'); observer.unobserve(e.target); } }), { threshold: .08 }); $$('.reveal').forEach(e => observer.observe(e)); } else $$('.reveal').forEach(e => e.classList.add('revealed')); $$('.audience-list details').forEach(d => d.addEventListener('toggle', () => { if (d.open) $$('.audience-list details').forEach(o => { if (o !== d) o.open = false; }); })); setLanguage(language);
